### ISSUE TITLE
TensorflowSVD Solver produces matmul errors.

### ISSUE THREAD

**Issue by dft-dutoit** [FitSNAP/FitSNAP#133]
TensorflowSVD solver style produces a size 1 mismatch after check_if_rank_zero completes. Having tested tensorflow modules on their own, outside of FitSNAP, they do not seem to be the issue as far as I can tell.

 ```
   ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----20May21------
Reading input...
Finished reading input
------------------
mpi4py version:  3.1.3
numpy version:  1.23.1
scipy version:  1.9.1
pandas version:  1.4.2
LAMMPS (29 Sep 2021 - Update 3)
  using 1 OpenMP thread(s) per MPI task
-----------
bulk_amo : Detected  3070  fitting on  3070  testing on  0
bulk_cryst : Detected  356  fitting on  356  testing on  0
cluster : Detected  30  fitting on  30  testing on  0
surf_amo : Detected  624  fitting on  0  testing on  623
split_test : Detected  450  fitting on  0  testing on  449
'scrape_configs' took 1166.68 ms on rank 0
>>> Matrix of descriptors takes up  0.0509 % of the total memory: 405.1683 GB
WARNING: Configuration has no SNAP neighbors
'process_configs' took 10627.55 ms on rank 0
2022-09-15 08:25:56.894656: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-15 08:25:56.934525: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.
'check_if_rank_zero' took 531.22 ms on rank 0
ERROR:fitsnap3.io.outputs.outputs:matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 31 is different from 30)
Traceback (most recent call last):
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/__main__.py", line 43, in main
    snap.perform_fit()
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/parallel_tools.py", line 220, in timed
    result = method(*args, **kw)
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/fitsnap.py", line 73, in perform_fit
    self.solver.error_analysis()
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/parallel_tools.py", line 248, in check_if_rank_zero
    return method(*args, **kw)
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/solvers/solver.py", line 71, in error_analysis
    self._all_error()
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/solvers/solver.py", line 92, in _all_error
    self._energy()
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/solvers/solver.py", line 104, in _energy
    self._errors([[0, testing]], ['*ALL'], "Energy", a, b, w)
  File "/data/chem-amais/scat7402/LAMMPS/march22/lib/python3.9/site-packages/fitsnap3/solvers/solver.py", line 350, in _errors
    true, pred = b_err, a_err @ self.fit
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 31 is different from 30)
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by rohskopf** [comment]
Thanks @dft-dutoit. Mind sharing the input script you used for this?

**Comment by dft-dutoit** [comment]
Absolutely, I was simply bringing it to your attention. Apologies for not noticing the note in the .py

Am I right in thinking that, as per the diagram in fitsnap3lib, the standard SVD solver can only use a single core?

And just to note - the standard SVD solver with all of my inputs has worked flawlessly up until now.

**Comment by rohskopf** [comment]
> Am I right in thinking that, as per the diagram in fitsnap3lib, the standard SVD solver can only use a single core?

Yes standard SVD uses a single core. Multiple cores are used for scraping and processing the configs. We have a scalapack solver which does parallel QR decomposition, the README is here: https://github.com/FitSNAP/FitSNAP/tree/master/fitsnap3lib/lib/scalapack_solver

> And just to note - the standard SVD solver with all of my inputs has worked flawlessly up until now.

If you share an input script and errors you get, I can help debug. It may be a LAMMPS version issue - you might need to update LAMMPS and/or FitSNAP. If that's the case, we have instructions here: https://fitsnap.github.io/usage.html#installation

**Comment by dft-dutoit** [comment]
Thanks, 

Unfortunately I am struggling to get the ScaLAPACK solver to build properly. It continues to give this error:

```
include_dirs=[get_include(), mpi4py.get_include(), scl_incl],
NameError: name 'scl_incl' is not defined
```
It seems from looking at the source code for setup.py that scl_incl is only created if scalapack_version=intelmkl. Thus, as I do not use scalapack via intelmkl it refuses to compile!

Thanks for the help so far.

**Comment by rohskopf** [comment]
@dft-dutoit Sorry, I wouldn't bother with the scalapack solver then, it needs to be brought up to date.

You can still run the standard linear solvers with `mpirun`; the data will be scraped in parallel and that will be much faster. Solving the matrix problem itself will happen on a single core, but it's fine. We fit up to 100k+ configurations with no issues, it doesn't take long to solve. 

Lemme know what the problem with the SVD solver is.

**Comment by rohskopf** [comment]
@dft-dutoit I'll share my progress here trying to get the scalapack solver working.

Until then, I recommend using the standard SVD solver which still parallellizes the data scraping and is fast.

I also don't have Intel MKL, my scalapack version is netlib.

In https://github.com/FitSNAP/FitSNAP/blob/master/fitsnap3lib/lib/scalapack_solver/setup.py, comment out `scl_include`:

`include_dirs=[get_include(), mpi4py.get_include()], #, scl_incl]`

Then manually add a path to scalapack lib folder in the `extra_compile_args` variable.

`extra_compile_args=["-DMKL_ILP64", "-m64", "-L/path/to/scalapack/2.1.0_3/lib/"],`

After this, I can run

`python setup.py build_ext --inplace`

And it sets up successfully, but when trying to install with

`python setup.py install`

I get an error:

`error: Could not find suitable distribution for Requirement.parse('UNKNOWN==0.0.0')`

So I think the install procedure for scalapack solvers needs some work.

**Comment by rohskopf** [comment]
Hi @dft-dutoit, the TensorflowSVD and scalapack solvers are not working for now. 

The standard SVD solver however is fine - is this working for you on the most recent FitSNAP branch?

If so, I'll close this issue because we don't have documentation or examples using TensorflowSVD or scalapack.
