### ISSUE TITLE
Error when quadraticflag=1 and chemsnap=1

### ISSUE THREAD

**Issue by rohskopf** [FitSNAP/FitSNAP#139]
This error can be reproduced when using these settings in any of the multi-element examples, we get a stack trace like:
```
(fitsnap) s1077702:WBe_PRB2019 adrohsk$ python -m fitsnap3 WBe-example.in --overwrite
Traceback (most recent call last):
  File "/Users/adrohsk/miniconda3/envs/fitsnap/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/adrohsk/miniconda3/envs/fitsnap/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/adrohsk/FitSNAP/fitsnap3/__main__.py", line 31, in <module>
    from fitsnap3lib.fitsnap import FitSnap
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/fitsnap.py", line 34, in <module>
    from fitsnap3lib.scrapers.scraper_factory import scraper
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/scrapers/scraper_factory.py", line 2, in <module>
    from fitsnap3lib.scrapers.scrape import Scraper
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/scrapers/scrape.py", line 37, in <module>
    from fitsnap3lib.io.output import output
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/output.py", line 6, in <module>
    config = Config()
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/input.py", line 26, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/input.py", line 47, in __init__
    self.parse_config()
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/input.py", line 118, in parse_config
    self.set_sections(tmp_config)
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/input.py", line 127, in set_sections
    self.sections[section] = new_section(section, tmp_config, self.args)
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/sections/section_factory.py", line 31, in new_section
    instance.__init__(section, config, args)
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/sections/calculator_sections/bispectrum.py", line 50, in __init__
    self._generate_b_list()
  File "/Users/adrohsk/FitSNAP/fitsnap3lib/io/sections/calculator_sections/bispectrum.py", line 123, in _generate_b_list
    self.blank2J = np.reshape(self.blank2J, len(self.blist))
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/adrohsk/miniconda3/envs/fitsnap/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/adrohsk/miniconda3/envs/fitsnap/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/adrohsk/miniconda3/envs/fitsnap/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: cannot reshape array of size 25520 into shape (194920,)
```
Just leaving this error here in case anyone else runs into it, can fix later.

**Comment by mitwood** [comment]
The raw number of descriptors that are generated from this pair of settings is... frightening. Since this produces a model that can't be run in LAMMPS, I am fine leaving this unresolved until that changes.
