### ISSUE TITLE
Example Fe Pytorch not working

### ISSUE THREAD

**Issue by hoba87** [FitSNAP/FitSNAP#141]
When trying to run the Fe Pytorch example, I get an error, see below. The Fe-Linear example seems to run fine.

```
--------------------------------------------------------------------------
CALCULATOR IO ----------
----- Global weights set: Overriding group weights.
----- Global training fraction set: Overriding group fractions.
DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.

    ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----23Sep22------
Reading input...
Finished reading input
------------------
mpi4py version:  3.0.3
numpy version:  1.21.6
scipy version:  1.5.4
pandas version:  1.1.1
LAMMPS (23 Jun 2022)
  using 1 OpenMP thread(s) per MPI task
-----------
Total wall time: 0:00:00
Using LAMMPSSNAP as FitSNAP calculator
Pytorch device is set to cuda
MD-bcc_Te300K : Detected  40  fitting on  40  testing on  0
EOS_100 : Detected  403  fitting on  403  testing on  0
BCC-HCP-transition : Detected  168  fitting on  168  testing on  0
liquid_mag_old : Detected  10  fitting on  10  testing on  0
point_def : Detected  8  fitting on  8  testing on  0
CCMC-bcc-hcp-elastic_Jun2020 : Detected  1358  fitting on  1358  testing on  0
liquid_nonmag : Detected  51  fitting on  51  testing on  0
'decorated_scrape_configs' took 2724.51 ms on rank 0
Nonlinear solver, preprocessing configs.
Traceback (most recent call last):
  File "/opt/FitSNAP/fitsnap3/__main__.py", line 46, in main
    snap.process_configs()
  File "/opt/FitSNAP/fitsnap3lib/fitsnap.py", line 128, in process_configs
    decorated_process_configs()
  File "/opt/FitSNAP/fitsnap3lib/parallel_tools.py", line 279, in timed
    result = method(*args, **kw)
  File "/opt/FitSNAP/fitsnap3lib/fitsnap.py", line 113, in decorated_process_configs
    self.calculator.preprocess_configs(configuration, i)
  File "/opt/FitSNAP/fitsnap3lib/calculators/lammps_base.py", line 55, in preprocess_configs
    raise e
  File "/opt/FitSNAP/fitsnap3lib/calculators/lammps_base.py", line 42, in preprocess_configs
    self._prepare_lammps()
  File "/opt/FitSNAP/fitsnap3lib/calculators/lammps_snap.py", line 53, in _prepare_lammps
    self._set_computes()
  File "/opt/FitSNAP/fitsnap3lib/calculators/lammps_snap.py", line 107, in _set_computes
    self._lmp.command(command)
  File "/opt/lammps/lammps-20220623-cuda/lib/python3.7/site-packages/lammps/core.py", line 582, in command
    self.lib.lammps_command(self.lmp,cmd)
  File "/opt/lammps/lammps-20220623-cuda/lib/python3.7/site-packages/lammps/core.py", line 49, in __exit__
    raise self.lmp._lammps_exception
Exception: ERROR: Illegal compute snap command (src/ML-SNAP/compute_snap.cpp:173)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/python-3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python/python-3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/FitSNAP/fitsnap3/__main__.py", line 55, in <module>
    main()
  File "/opt/FitSNAP/fitsnap3lib/parallel_tools.py", line 279, in timed
    result = method(*args, **kw)
  File "/opt/FitSNAP/fitsnap3/__main__.py", line 51, in main
    output.exception(e)
TypeError: exception() missing 1 required positional argument: 'err'
```

**Comment by rohskopf** [comment]
Hi @hoba87, your output says

`LAMMPS (23 Jun 2022)`

But we need the most recent LAMMPS version for fitting neural networks. 

Please get the latest LAMMPS with `git clone https://github.com/lammps/lammps` and build with Python according to [https://fitsnap.github.io/Pytorch.html#getting-started](https://fitsnap.github.io/Pytorch.html#getting-started).

**Comment by rohskopf** [comment]
In the meantime, I will put a more descriptive error message to let people know they should update their LAMMPS installation.

**Comment by hoba87** [comment]
Ok, I thought the Lammps version was very recent. However with the patch release 15 Sep 2022 it is working. Thank you!
