### ISSUE TITLE
NN fitting to energies without forces fails

### ISSUE THREAD

**Issue by dmozapiain2001** [FitSNAP/FitSNAP#148]
Running the script FitSNAP/examples/Fe_Pytorch_NN/Fe-example.in with forces = 0 fails to run with this error

`----- Global weights set: Overriding group weights.
----- Global training fraction set: Overriding group fractions.

    ______ _  __  _____  _   __ ___     ____  
   / ____/(_)/ /_/ ___/ / | / //   |   / __ \ 
  / /_   / // __/\__ \ /  |/ // /| |  / /_/ /
 / __/  / // /_ ___/ // /|  // ___ | / ____/ 
/_/    /_/ \__//____//_/ |_//_/  |_|/_/      

-----23Sep22------
Reading input...
Finished reading input
------------------
No mpi4py detected, using fitsnap stubs...
numpy version:  1.23.1
scipy version:  1.9.1
pandas version:  1.4.4
LAMMPS (15 Sep 2022)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
-----------
Total wall time: 0:00:00
Using LAMMPSSNAP as FitSNAP calculator
Pytorch device is set to cpu
Displaced_A15 : Detected  9  fitting on  9  testing on  0
Displaced_BCC : Detected  9  fitting on  9  testing on  0
Displaced_FCC : Detected  9  fitting on  9  testing on  0
Elastic_BCC : Detected  100  fitting on  100  testing on  0
Elastic_FCC : Detected  100  fitting on  100  testing on  0
GSF_110 : Detected  22  fitting on  22  testing on  0
GSF_112 : Detected  22  fitting on  22  testing on  0
Liquid : Detected  3  fitting on  3  testing on  0
Surface : Detected  7  fitting on  7  testing on  0
Volume_A15 : Detected  30  fitting on  30  testing on  0
Volume_BCC : Detected  21  fitting on  21  testing on  0
Volume_FCC : Detected  31  fitting on  31  testing on  0
'decorated_scrape_configs' took 421.99 ms on rank 0
Nonlinear solver, preprocessing configs.
>>> Matrix of descriptors and descriptor derivatives takes up  0.0004 % of the total memory: 270.4244 GB
Traceback (most recent call last):
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3/__main__.py", line 46, in main
    snap.process_configs()
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/fitsnap.py", line 136, in process_configs
    decorated_process_configs()
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/parallel_tools.py", line 279, in timed
    result = method(*args, **kw)
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/fitsnap.py", line 119, in decorated_process_configs
    self.calculator.create_a()
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/calculators/lammps_base.py", line 22, in create_a
    super().create_a()
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/calculators/calculator.py", line 95, in create_a
    self.pt.new_slice_c()
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/parallel_tools.py", line 601, in new_slice_c
    assert sum(sub_c_sizes) == len(self.shared_arrays['c'].array)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmonte/anaconda3/envs/Fitsnap_NN/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dmonte/anaconda3/envs/Fitsnap_NN/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3/__main__.py", line 55, in <module>
    main()
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3lib/parallel_tools.py", line 279, in timed
    result = method(*args, **kw)
  File "/mnt/sdb1/dmonte/Fitsnap_oct_22/FitSNAP/examples/Ta_PyTorch_NN/fitsnap3/__main__.py", line 51, in main
    output.exception(e)
TypeError: Output.exception() missing 1 required positional argument: 'err'`

I have also set the flag dgradflag = 0 and try rerunning and still obtainig the same error.

**Comment by rohskopf** [comment]
Fixed in https://github.com/FitSNAP/FitSNAP/pull/147
