### ISSUE TITLE
SymPy required when not fitting ACE potentials

### ISSUE THREAD

**Issue by megmcca** [FitSNAP/FitSNAP#154]
As stated in title, using FitSNAP as of PR merge #110.
Similar to the PyTorch issue #146.

--------------------------------------------------------------------------------------------------------------------------------------------
Stack trace:
(fs3) megmcca: ~/fitsnap/examples/Ta_Linear_JCP2014 $ python -m fitsnap3 --overwrite Ta-example.in 
Traceback (most recent call last):
  File "/home/megmcca/miniconda3/envs/fs3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/megmcca/miniconda3/envs/fs3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3/__main__.py", line 31, in <module>
    from fitsnap3lib.fitsnap import FitSnap
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/fitsnap.py", line 34, in <module>
    from fitsnap3lib.scrapers.scraper_factory import scraper
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/scrapers/scraper_factory.py", line 2, in <module>
    from fitsnap3lib.scrapers.scrape import Scraper
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/scrapers/scrape.py", line 32, in <module>
    from fitsnap3lib.io.input import Config
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/io/input.py", line 5, in <module>
    from fitsnap3lib.io.sections.section_factory import new_section
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/io/sections/section_factory.py", line 6, in <module>
    from fitsnap3lib.io.sections.calculator_sections.ace import Ace
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/io/sections/calculator_sections/ace.py", line 3, in <module>
    from fitsnap3lib.lib.sym_ACE.rpi_lib import *
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/lib/sym_ACE/rpi_lib.py", line 1, in <module>
    from fitsnap3lib.lib.sym_ACE.lib.coupling_tree import * 
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/lib/sym_ACE/lib/coupling_tree.py", line 1, in <module>
    from fitsnap3lib.lib.sym_ACE.young import * 
  File "/home/megmcca/projects/fitsnap/my_fork/fitsnap3lib/lib/sym_ACE/young.py", line 1, in <module>
    from sympy.combinatorics import Permutation
ModuleNotFoundError: No module named 'sympy'

**Comment by rohskopf** [comment]
We updated the installation instructions (https://fitsnap.github.io/Quick.html) to include sympy but since it's a large package, maybe we should do the same thing we did with torch.

**Comment by megmcca** [comment]
Good that the docs are up to date! 
Sounds like this is probably a one-off problem for us with current installs - also had to install PyYAML (which you have in the docs too).
Happy to pitch in if you do want to go the torch route with SymPy and PyYAML, just let me know!
