### ISSUE TITLE
Fix GASNAP with some examples.

### ISSUE THREAD

**Issue by rohskopf** [FitSNAP/FitSNAP#230]
Sometimes we see this error with GASNAP (thanks Vayle for supplying output) :
```
Traceback (most recent call last):
  File "/nscratch/vveracr/GAFit1/libmod_optimize.py", line 62, in <module>
    rmse_e = errs1.iloc[:,2].to_numpy()
AttributeError: 'list' object has no attribute 'iloc'
```

and

```
Traceback (most recent call last):
  File "/nscratch/vveracr/GAFit1/libmod_optimize.py", line 560, in <module>
    genetic_algorithm()
  File "/ascldap/users/vveracr/FitSNAP/fitsnap3lib/parallel_tools.py", line 322, in check_if_rank_zero
    return method(*args, **kw)
  File "/nscratch/vveracr/GAFit1/libmod_optimize.py", line 529, in genetic_algorithm
    cs = crossover(p1,p2,len(gtks),w_combo_delta,ef_rat_delta)
  File "/ascldap/users/vveracr/FitSNAP/fitsnap3lib/parallel_tools.py", line 322, in check_if_rank_zero
    return method(*args, **kw)
  File "/nscratch/vveracr/GAFit1/libmod_optimize.py", line 193, in crossover
    pt = np.random.randint(1, ne-2)
  File "mtrand.pyx", line 781, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1334, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
```

**Comment by megmcca** [comment]
From my experience, the first error occurs when using MPI and for the moment appears relatively harmless

The second error happens when there are too few training groups (or maybe structures?) - I've started a (currently draft) PR #231 that will handle this case with an informative crash
It may actually be more about the number of structures, but I haven't tested it extensively
