### ISSUE TITLE
distutils package is removed in python version 3.12

### ISSUE THREAD

**Issue by alphataubio** [FitSNAP/FitSNAP#267]
>(fitsnap-venv) mitch@macmini Ta_Linear_JCP2014 % mpirun -np 8 python3 -m fitsnap3 Ta-example.in
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3/__main__.py", line 32, in <module>
    from fitsnap3lib.fitsnap import FitSnap
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3lib/fitsnap.py", line 36, in <module>
    from fitsnap3lib.calculators.calculator_factory import calculator
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3lib/calculators/calculator_factory.py", line 6, in <module>
    from fitsnap3lib.calculators.lammps_custom import LammpsCustom
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3lib/calculators/lammps_custom.py", line 2, in <module>
    from fitsnap3lib.io.input import Config
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3lib/io/input.py", line 5, in <module>
    from fitsnap3lib.io.sections.section_factory import new_section
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3lib/io/sections/section_factory.py", line 2, in <module>
    from fitsnap3lib.io.sections.sections import Section
  File "/Users/mitch/Dropbox/lammps/FitSNAP-alphataubio/fitsnap3lib/io/sections/sections.py", line 2, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'

https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed

** need to add setuptools to pip install **, see `Installation.rst` in https://github.com/FitSNAP/FitSNAP/pull/266

**Comment by mitwood** [comment]
Good catch, thanks! This is now reflected in Installation.rst
