### ISSUE TITLE
Install with LAMMPS

### ISSUE THREAD

**Issue by dft-dutoit** [FitSNAP/FitSNAP#67]
Hi, 

I have a working install of LAMMPS with python, ml-snap and gpu support enabled via kokkos. However, upon using the pip (and/or conda) version of FitSNAP, I get errors when attempting the examples.

```
For Ta_Linear_JCP2014 I get the following: 
-----------
Reading input...
Finished reading input
mpi4py version:  3.1.2
numpy version:  1.21.2
scipy version:  1.7.2
pandas version:  1.3.4
-----------
ERROR:fitsnap3.io.outputs.outputs:[Errno 2] No such file or directory: '/data/chem-amais/scat7402//data/chem-amais/scat7402/FitSNAP/examples/Ta_Linear_JCP2014/JSON/random_sampling'
Traceback (most recent call last):
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/__main__.py", line 42, in main
    snap.scrape_configs()
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/parallel_tools.py", line 205, in timed
    result = method(*args, **kw)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/fitsnap.py", line 52, in scrape_configs
    self.scraper.scrape_groups()
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/scrapers/json_scraper.py", line 17, in scrape_groups
    super().scrape_groups()
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/scrapers/scrape.py", line 88, in scrape_groups
    folder_files = listdir(folder)
FileNotFoundError: [Errno 2] No such file or directory: '/data/chem-amais/scat7402//data/chem-amais/scat7402/FitSNAP/examples/Ta_Linear_JCP2014/JSON/random_sampling'

```
For WBe_PBR2019 I get the following:

```
Reading input...
Trouble reading input, exiting...
Traceback (most recent call last):
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/__init__.py", line 60, in <module>
    pt.exception(e)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/parallel_tools.py", line 446, in exception
    raise err
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/__init__.py", line 55, in <module>
    from .io.input import config
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/input.py", line 93, in <module>
    config = Config()
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/input.py", line 16, in __init__
    self.parse_config()
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/input.py", line 74, in parse_config
    self.set_sections(tmp_config)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/input.py", line 88, in set_sections
    self.sections[section] = new_section(section, tmp_config, self.args)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/sections/section_factory.py", line 8, in new_section
    instance.__init__(section, config, args)
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/sections/bispectrum.py", line 12, in __init__
    self.twojmax = self.get_value("BISPECTRUM", "twojmax", "6", "int")
  File "/data/chem-amais/scat7402/Anaconda_lammps/lib/python3.8/site-packages/fitsnap3/io/sections/sections.py", line 47, in get_value
    return convert(self._config.get(section, key, fallback=fallback))
ValueError: invalid literal for int() with base 10: '8 8'
```

I understand that I may have failed in some case to make sure the install is working properly, however when calling lammps via python there is no issue, and similarly fitsnap3 seems to initialise without error. However, when running these errors come into the case. With the WBe, I wonder whether it is the existence of two elements that is confusing fitsnap? 

EDIT: Upon further inspection, it appears that updates have broken compatibility with the infiles on these examples. By making small changes using TEMPLATE.in it's possible to get them running again, and the results are very similar.

Best, 
Daniel

**Comment by charlessievers** [comment]
Hey Daniel,

Thank you for submitting the issue. The pip has been out of date for a while, but now that I know people are attempting to use it I will try and update it today.

Best,
Charlie

**Comment by dft-dutoit** [comment]
Hi Charlie, 

Thanks for this, I would be very happy to use the version documented here, but wasn't totally confident in the installation process. If you had any advice about how to install the git version I would be interested in that too, as I am looking to experiment with SNAP and qSNAP across various architectures, so having both as an option would be perfect!

Thanks again,
Daniel

**Comment by charlessievers** [comment]
Hello Daniel,

I believe the pip should be updated now. Let me know otherwise.

I would recommend sticking to either pip or git cloning as having both can be a nightmare for a python environment.

Best,
Charlie

**Comment by dft-dutoit** [comment]
Thanks Charlie,

I'll get back in touch if I need anything further, is git the preferred method? If so I'll try and get on top of it!

**Comment by charlessievers** [comment]
Git is definitely the preferred method. We may phase out pip support if there is a lack of interest in it.

**Comment by dft-dutoit** [comment]
Ah okay - I'll try and figure out the git install procedure, I think I got it a bit wrong earlier this week. Thanks for all your help.
